language: python
dist: xenial
before_install:
  - cd ./app
install:
  - pip install -r requirements.txt
script:
  - pytest
deploy:
  - provider: heroku
    api_key:
      secure: WbyJkEBqRvpVL8E+oeTrjGtYTi4tobVLDkXT65Y4JPRba60JC0pXq6+uiS2muRZbMVyKtcPYed5N85NOYFlQG/NSQ482X40xLLnl36mMduuRgn85UbslJWNHaqGSNkb5KCoqlrXBfJq5fji4Ec241weF0DoBM/vnjoRMMwfZuzlU4B9Au1RVnpdQfwZpZn9DbmX3EQc/ECA1ds4VOOfVvaD9pLMvysfdPqWuk3ETa7KLQ5pXMuToebVa1pKwAxzZdk3Vw+oYZNLjGEDfh0Hd8rcwcdBG4D7Cxke+odDDq4ygOx9RMVHW6RXD29f/iMWwBo0Ch7xXz/SSfjD2NZ17uz04XubKt9tvc+Sexj+5Ol621a322mm7IF2j0ju5NPnJ1FVND/NGBsAWzqKv5DS2JB+sN/EaAXlkwiANQt3J7avyh/DX8TnOc3cem/cQyDK5k66wRT+pKlsjsZKziwto0JbVqRWFUgngYASj03PavBqGv5WgzlWhE72ClcGi8YwoAYDoMo9FYM8/cr7V0Y/2nTYS2ASE2rwhXI2KuGQInO+AhAXN10mJp4U7Df/SwIn3hgIiCdSzXgnUAYrrn7tjSc0NqI05TB796nExiwT/GxzI1fk7WeQNjw3mtf/yjfxH6Q/UXo3Y/eSiDsjqPVyykoFlv11VVDAq/i4uyx1Oyz4=
